services:
  - type: web
    name: contemos-juntos
    env: node
    region: oregon
    plan: free
    
    # Build command
    buildCommand: bash build.sh
    
    # Start command
    startCommand: cd backend && npm start
    
    # Puerto
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production

